### ISSUE TITLE
Feature request: Support auto-provisioning checks

### ISSUE THREAD

**Issue by bertiewils** [danidelvalle/healthchecks-decorator#348]
Healthchecks.io supports auto-provisioning, where they can auto-create the check if the specified slug does not exist.

See https://blog.healthchecks.io/2023/07/new-feature-check-auto-provisioning/

Adding `?create=1` to the end of the url interferes with the start signal when `HEALTHCHECK_SEND_START` is enabled. That becomes `?create=1/start`, when it should be `/start?create=1`.

**Comment by danidelvalle** [comment]
Thanks @bertiewils for the suggestion! I've already implemented this feature. You can now use auto-provisioning by adding ?create=1 to the URL without any interference 😊
